### ISSUE TITLE
Paramaters are not designed well

### ISSUE THREAD

**Issue by raxetul** [favalex/modbus-cli#4]
Acces syntax is hard to understand.
endian swap of pyhton "<" should not be exposed(for non python developers might not understand how to use). "<" char is used for shell redirections, so an endian parameter "-e LITTLE" or "-e BIG" would be better(escaping it makes token harder.). Also changing endian   with "<" char does not work at the moment. 
I have to look at your code and debug it to understand how it works but this should not be in this way.
Explicit argument for each Acces  should be added into argument list.

**Comment by favalex** [comment]
Having a syntax based on python's own struct module https://docs.python.org/3/library/struct.html#format-strings was the main motivation behind writing yet another modbus CLI tool, so that's not gonna change.
